version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gocritic
    - misspell
    - unconvert
    - errorlint
    - exhaustive
    - copyloopvar
    - intrange
    - gosec
    - bodyclose
    - nolintlint
    - usestdlibvars
    - nakedret
    - whitespace
    - durationcheck
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
    paths:
      - docs
      - examples

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - exitAfterDefer

formatters:
  enable:
    - goimports

output:
  sort-order:
    - file

run: {}
